# Generated by Django 4.0.2 on 2022-02-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Contact_Response',
        ),
    ]
