# Generated by Django 4.0.4 on 2022-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_person_contact_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('Timestamp', models.CharField(max_length=100, verbose_name='Timestamp')),
                ('Gen_Bear_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('Gen_Phase1_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('Hyd_Oil_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('HVTrafo_Phase2_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('Gear_Bear_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('Gear_Oil_Temp_Avg', models.FloatField(verbose_name=0.0)),
                ('loss', models.FloatField(verbose_name=0.0)),
                ('threshold', models.FloatField(verbose_name=0.0)),
                ('anomaly', models.BooleanField(default=False)),
                ('color', models.FloatField(verbose_name=0.0)),
                ('dayTill', models.IntegerField()),
                ('component', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('dayofyear', models.IntegerField()),
                ('dayName', models.CharField(max_length=100)),
                ('monthName', models.CharField(max_length=100)),
            ],
        ),
    ]
